// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: flag.proto

package flagpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EnvironmentFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvironmentID string  `protobuf:"bytes,1,opt,name=environmentID,proto3" json:"environmentID,omitempty"`
	Flags         []*Flag `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
}

func (x *EnvironmentFlags) Reset() {
	*x = EnvironmentFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvironmentFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentFlags) ProtoMessage() {}

func (x *EnvironmentFlags) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentFlags.ProtoReflect.Descriptor instead.
func (*EnvironmentFlags) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{0}
}

func (x *EnvironmentFlags) GetEnvironmentID() string {
	if x != nil {
		return x.EnvironmentID
	}
	return ""
}

func (x *EnvironmentFlags) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeatureKey string `protobuf:"bytes,1,opt,name=featureKey,proto3" json:"featureKey,omitempty"`
	Value      bool   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Flag) Reset() {
	*x = Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{1}
}

func (x *Flag) GetFeatureKey() string {
	if x != nil {
		return x.FeatureKey
	}
	return ""
}

func (x *Flag) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type EnvironmentFlagQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvironmentID string `protobuf:"bytes,1,opt,name=environmentID,proto3" json:"environmentID,omitempty"`
}

func (x *EnvironmentFlagQuery) Reset() {
	*x = EnvironmentFlagQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvironmentFlagQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentFlagQuery) ProtoMessage() {}

func (x *EnvironmentFlagQuery) ProtoReflect() protoreflect.Message {
	mi := &file_flag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentFlagQuery.ProtoReflect.Descriptor instead.
func (*EnvironmentFlagQuery) Descriptor() ([]byte, []int) {
	return file_flag_proto_rawDescGZIP(), []int{2}
}

func (x *EnvironmentFlagQuery) GetEnvironmentID() string {
	if x != nil {
		return x.EnvironmentID
	}
	return ""
}

var File_flag_proto protoreflect.FileDescriptor

var file_flag_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x6c, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x5a, 0x0a, 0x10, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x05,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x3c,
	0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x14,
	0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x32, 0x5a, 0x0a, 0x0b, 0x46, 0x6c,
	0x61, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73,
	0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x16, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x6c, 0x61, 0x67, 0x73, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_flag_proto_rawDescOnce sync.Once
	file_flag_proto_rawDescData = file_flag_proto_rawDesc
)

func file_flag_proto_rawDescGZIP() []byte {
	file_flag_proto_rawDescOnce.Do(func() {
		file_flag_proto_rawDescData = protoimpl.X.CompressGZIP(file_flag_proto_rawDescData)
	})
	return file_flag_proto_rawDescData
}

var file_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flag_proto_goTypes = []interface{}{
	(*EnvironmentFlags)(nil),     // 0: grpc.EnvironmentFlags
	(*Flag)(nil),                 // 1: grpc.Flag
	(*EnvironmentFlagQuery)(nil), // 2: grpc.EnvironmentFlagQuery
}
var file_flag_proto_depIdxs = []int32{
	1, // 0: grpc.EnvironmentFlags.flags:type_name -> grpc.Flag
	2, // 1: grpc.FlagService.GetEnvironmentFlags:input_type -> grpc.EnvironmentFlagQuery
	0, // 2: grpc.FlagService.GetEnvironmentFlags:output_type -> grpc.EnvironmentFlags
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flag_proto_init() }
func file_flag_proto_init() {
	if File_flag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvironmentFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvironmentFlagQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flag_proto_goTypes,
		DependencyIndexes: file_flag_proto_depIdxs,
		MessageInfos:      file_flag_proto_msgTypes,
	}.Build()
	File_flag_proto = out.File
	file_flag_proto_rawDesc = nil
	file_flag_proto_goTypes = nil
	file_flag_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlagServiceClient is the client API for FlagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlagServiceClient interface {
	GetEnvironmentFlags(ctx context.Context, in *EnvironmentFlagQuery, opts ...grpc.CallOption) (*EnvironmentFlags, error)
}

type flagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlagServiceClient(cc grpc.ClientConnInterface) FlagServiceClient {
	return &flagServiceClient{cc}
}

func (c *flagServiceClient) GetEnvironmentFlags(ctx context.Context, in *EnvironmentFlagQuery, opts ...grpc.CallOption) (*EnvironmentFlags, error) {
	out := new(EnvironmentFlags)
	err := c.cc.Invoke(ctx, "/grpc.FlagService/GetEnvironmentFlags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlagServiceServer is the server API for FlagService service.
type FlagServiceServer interface {
	GetEnvironmentFlags(context.Context, *EnvironmentFlagQuery) (*EnvironmentFlags, error)
}

// UnimplementedFlagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlagServiceServer struct {
}

func (*UnimplementedFlagServiceServer) GetEnvironmentFlags(context.Context, *EnvironmentFlagQuery) (*EnvironmentFlags, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnvironmentFlags not implemented")
}

func RegisterFlagServiceServer(s *grpc.Server, srv FlagServiceServer) {
	s.RegisterService(&_FlagService_serviceDesc, srv)
}

func _FlagService_GetEnvironmentFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvironmentFlagQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).GetEnvironmentFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FlagService/GetEnvironmentFlags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).GetEnvironmentFlags(ctx, req.(*EnvironmentFlagQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FlagService",
	HandlerType: (*FlagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnvironmentFlags",
			Handler:    _FlagService_GetEnvironmentFlags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flag.proto",
}
